// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

error ZeroAddress();
error InvalidMatchId();
error InvalidContestId();
error MatchAlreadyExists();
error MatchNotFound();
error MatchAlreadyHasContest(uint256 matchId, uint256 contestId);
error InvalidArrayLength();
error TooManyPlayers();
error InvalidMatchTiming();
error InvalidPlayerRole();
error InvalidTeamSide();
error PlayerPoolFrozen(uint256 matchId);
error PlayerNotAllowed(uint256 matchId, uint16 playerId);
error MatchLocked(uint256 matchId);
error DuplicatePlayer(uint16 playerId);
error InvalidStatusTransition();
error SquadNotFound(uint256 tokenId);
error InvalidSquadComposition();
error CaptainNotInSquad();
error ViceCaptainNotInSquad();
error CaptainViceCaptainSame();
error NotTokenOwner();
error TokenTransferLocked(uint256 tokenId);
error SquadMatchMismatch(uint256 expectedMatchId, uint256 actualMatchId);
error ContestAlreadyExists();
error ContestNotFound();
error ContestFull();
error ContestFinalizedAlready();
error ContestNotFinalized();
error ContestCancelled();
error ContestActive();
error InvalidContestConfig();
error WrongEntryFee(uint256 expected, uint256 actual);
error WalletEntryLimitReached();
error TokenAlreadyEntered();
error PassportAlreadyMinted(address user);
error PassportNotFound(address user);
error SoulboundTokenTransfer(uint256 tokenId);
error StatsAlreadySubmitted(uint256 matchId);
error StatsBeforeMatchLock(uint256 matchId);
error StatsNotSubmitted(uint256 matchId);
error NotEnoughEntries();
error NoReward();
error NoRefund();
error NoTreasuryBalance();
error NativeTransferFailed();
