export const publicEnv = {
  NEXT_PUBLIC_WIREFLUID_CHAIN_ID: process.env.NEXT_PUBLIC_WIREFLUID_CHAIN_ID,
  NEXT_PUBLIC_WIREFLUID_RPC_URL: process.env.NEXT_PUBLIC_WIREFLUID_RPC_URL,
  NEXT_PUBLIC_MATCH_REGISTRY: process.env.NEXT_PUBLIC_MATCH_REGISTRY,
  NEXT_PUBLIC_FANTASY_TEAM_NFT: process.env.NEXT_PUBLIC_FANTASY_TEAM_NFT,
  NEXT_PUBLIC_LEGACY_PASSPORT: process.env.NEXT_PUBLIC_LEGACY_PASSPORT,
  NEXT_PUBLIC_SCORE_MANAGER: process.env.NEXT_PUBLIC_SCORE_MANAGER,
  NEXT_PUBLIC_CONTEST_MANAGER: process.env.NEXT_PUBLIC_CONTEST_MANAGER
} as const;

